arm:
# Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # position controller
  # joint1_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint1
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.5, d: 1.0}
  
  # joint3_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint3
  #   pid: {p: 100.0, i: 0.5, d: 1.0}
  
  # joint4_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint4
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint5_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint5
  #   pid: {p: 100.0, i: 0.5, d: 1.0}
  
  # joint6_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint6
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # gripper_finger1_joint_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: gripper_finger1_joint
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  
  # # Velocity Controllers ---------------------------------------
  # joint1_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint1
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint2_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint3_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint3
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint4_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint4
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint5_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint5
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # joint6_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: joint6
  #   pid: {p: 100.0, i: 0.5, d: 1.0}

  # gripper_finger1_joint_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: gripper_finger1_joint
  #   pid: {p: 100.0, i: 0.5, d: 1.0}
