gazebo_ros_control/pid_gains:
  joint_a1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
  joint_a2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
  joint_a3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
  joint_a4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
  joint_a5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
  joint_a6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


